export enum EventsType {
    BuyerChange = "BuyerChange",
    BuyerEmpty = "BuyerEmpty",
    CartChange = "CartChange",
    CartEmpty = "CartEmpty",
    ProductNewCatalog = "ProductNewCatalog",
    ProductChooseCurrent = "ProductChooseCurrent",
    OrderNew = "OrderNew",
    OpenBasket = "OpenBasket",
    ModalCloseButton = "ModalCloseButton",
    CardOpen = "CardOpen",
    CardButtonAction = "CardButtonAction",
    CardRemoveButton = "CardRemoveButton",
    OrderChooseCash = "OrderChooseCash",
    OrderChooseCard = "OrderChooseCard",
    OrderAddressChange = "OrderAddressChange",
    OrderEmailChange = "OrderEmailChange",
    OrderPhoneChange = "OrderPhoneChange",
    ContactsNew = "ContactsNew",
    OrderSend = "OrderSend",
    ResultOkButton = "ResultOkButton"
}